#pragma once
#include "efi/types.h"
#include "efi/protocols/devicepath.h"

#define EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL_GUID {0x6b30c738,0xa391,0x11d4,{0x9a,0x3b,0x00,0x90,0x27,0x3f,0xc1,0x4d}}

typedef struct _EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL;

typedef EFI_STATUS(EFIAPI *EFI_PLATFORM_DRIVER_OVERRIDE_GET_DRIVER) (
	IN    EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL       *This,
	IN    EFI_HANDLE                                  ControllerHandle,
	IN OUT EFI_HANDLE                               *DriverImageHandle
	);

typedef EFI_STATUS(EFIAPI *EFI_PLATFORM_DRIVER_OVERRIDE_GET_DRIVER_PATH) (
	IN EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL             *This,
	IN EFI_HANDLE                                        ControllerHandle,
	IN OUT EFI_DEVICE_PATH_PROTOCOL                      **DriverImagePath
	);

typedef EFI_STATUS(EFIAPI *EFI_PLATFORM_DRIVER_OVERRIDE_DRIVER_LOADED) (
	IN EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL         *This,
	IN EFI_HANDLE                                    ControllerHandle,
	IN EFI_DEVICE_PATH_PROTOCOL                      *DriverImagePath,
	IN EFI_HANDLE                                    DriverImageHandle
	);

struct _EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL {
	EFI_PLATFORM_DRIVER_OVERRIDE_GET_DRIVER           GetDriver;
	EFI_PLATFORM_DRIVER_OVERRIDE_GET_DRIVER_PATH      GetDriverPath;
	EFI_PLATFORM_DRIVER_OVERRIDE_DRIVER_LOADED        DriverLoaded;
};

#define EFI_BUS_SPECIFIC_DRIVER_OVERRIDE_PROTOCOL_GUID {0x3bc1b285,0x8a15,0x4a82,{0xaa,0xbf,0x4d,0x7d,0x13,0xfb,0x32,0x65}}

typedef struct _EFI_BUS_SPECIFIC_DRIVER_OVERRIDE_PROTOCOL EFI_BUS_SPECIFIC_DRIVER_OVERRIDE_PROTOCOL;

typedef EFI_STATUS(EFIAPI *EFI_BUS_SPECIFIC_DRIVER_OVERRIDE_GET_DRIVER) (
	IN EFI_BUS_SPECIFIC_DRIVER_OVERRIDE_PROTOCOL        *This,
	IN OUT EFI_HANDLE                                   *DriverImageHandle
	);

struct _EFI_BUS_SPECIFIC_DRIVER_OVERRIDE_PROTOCOL {
	EFI_BUS_SPECIFIC_DRIVER_OVERRIDE_GET_DRIVER GetDriver;
};

#define EFI_DRIVER_FAMILY_OVERRIDE_PROTOCOL_GUID {0xb1ee129e,0xda36,0x4181,{0x91,0xf8,0x04,0xa4,0x92,0x37,0x66,0xa7}}

typedef struct _EFI_DRIVER_FAMILY_OVERRIDE_PROTOCOL EFI_DRIVER_FAMILY_OVERRIDE_PROTOCOL;

typedef UINT32(EFIAPI *EFI_DRIVER_FAMILY_OVERRIDE_GET_VERSION) (IN EFI_DRIVER_FAMILY_OVERRIDE_PROTOCOL *This);

struct _EFI_DRIVER_FAMILY_OVERRIDE_PROTOCOL {
	EFI_DRIVER_FAMILY_OVERRIDE_GET_VERSION        GetVersion;
};